site:
  title: Hackfables
  start_page: hackfables::preface.adoc
  url: https://hackfables.org
content:
  sources:
    - url: .
      branches: HEAD
ui:
  bundle:
    url: https://cdn.jsdelivr.net/npm/@antora/ui-default@3.1.7/dist/ui-bundle.zip
    snapshot: true
output:
  dir: build/site
